output: bPk
multipole: 3
wedge: 3
skycut: 3
z: [0.57, 0.57, 0.32]
with_redshift_bin: False
zz: []
nz: []
with_AP: True
z_AP: [0.57, 0.57, 0.32]
Omega_m_AP: 0.310
with_window: True
windowPk: [pybird/Window/pynest_BOSS_CMASS_NGC_z057, pybird/Window/pynest_BOSS_CMASS_SGC_z057, pybird/Window/pynest_BOSS_LOW_NGC_z032]
windowCf: [pybird/Window/window_BOSS_CMASS_NGC_z0p57.dat, pybird/Window/window_BOSS_CMASS_SGC_z0p57.dat, pybird/Window/window_BOSS_LOWZ_NGC_z0p32.dat]
binning: False
with_fibercol: True

with_stoch: True
model: 1

with_bao: False

xmin: [0.01, 0.01, 0.01]
#xmax: [0.23, 0.23, 0.2]
xmax0: [0.4, 0.4, 0.35]
xmax1: [0.23, 0.23, 0.2]

with_bao: True
zbao: [0.57, 0.57, 0.32]
baoH: [97.982, 91.8465, 68.8476]
baoD: [2160.59, 2215.45, 1258.60]
rs_rescale: [1., 1., 1.]
rd_fid_in_Mpc: [148.11, 148.11, 148.11]

covmat_file: [pybird/Wedges/linear/Cov_w3_LightConeHector_cmass_ngc.dat, pybird/Wedges/linear/Cov_w3_LightConeHector_cmass_sgc.dat, pybird/Wedges/linear/Cov_w3_LightConeHector_lowz_ngc.dat]
spectrum_file: [pybird/Wedges/linear/w3_LightConeHector_cmass_ngc_data.dat, pybird/Wedges/linear/w3_LightConeHector_cmass_sgc_data.dat, pybird/Wedges/linear/w3_LightConeHector_lowz_ngc_data.dat]

nd: 4.5e-4
km: 0.7

with_bbn: True
omega_b_BBNcenter: 0.02235
omega_b_BBNsigma: 0.0005